version: "3.7"

services:
  iotfreezer-frontend:
    container_name: iotfreezer-frontend
    build:
      context: .
    ports:
      - ${SERVER_PORT}:80
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
